### ISSUE TITLE
Upload processing disconnects from server

### ISSUE THREAD

**Issue by eanders** [abtassociates/eva#118]
**Describe the bug**
When uploading a hashed CSV set, the site disconnects from the server.

**To Reproduce**
1. Go to https://hmis.abtsites.com/eva/
2. Upload a hashed CSV (zipped)
3. Wait ~30 seconds
4. See error:

<img width="1483" alt="Screenshot 2022-12-19 at 3 52 53 PM" src="https://user-images.githubusercontent.com/1346876/208523281-c13a3efb-2e6c-4b46-9ba8-d68db0c973ee.png">

**Expected behavior**
It shouldn't disconnect

**Desktop (please complete the following information):**
 - Operating System: Mac OS
 - Browser: Chrome or Safari

**Comment by kiadso** [comment]
Thank you Elliott! Whenever you try this, is it always stopping on "Assessing your data quality..."? Also, once it's grayed out, does the Processing finish?

Also, did you try this at different times or was this all in one go? (If you try again now, does it still happen?)

Thanks again-

**Comment by eanders** [comment]
Attempted two or three times earlier, all around the same time. Just tried again.  It appears to be stalled in the same spot.  I'll leave it open for a while and report back, but the others never re-connected, but I only gave them a couple minutes after the disconnect.

**Comment by eanders** [comment]
Yep, it appears stuck

**Comment by kiadso** [comment]
Ok, thank you, Elliot- I'm checking with our back-end folks to see if any R errors were thrown. If you do right-click and Inspect and Console, do you find anything interesting there?

**Comment by eanders** [comment]
<img width="1547" alt="Screenshot 2022-12-20 at 2 32 51 PM" src="https://user-images.githubusercontent.com/1346876/208751197-a81788a4-5f72-449a-b317-a90ac02b59d4.png">

**Comment by eccovia-csmith** [comment]
We are seeing the same issue after uploading a hashed csv. Only errors in the console are related to missing fonts as Elliot has shown in the screenshot

**Comment by kiadso** [comment]
Hi eccovia!

Thanks for the confirmation- Elliot is working on sending us a sample dataset from their system so we can test this in our development environment. In the meantime, I will raise the font issue with our server team. 

I have a question for both of you- if you collapse both of the help boxes, can you see how the File Structure Analysis turned out? Like does it list any Errors behind the gray?

Thank you!

**Comment by eccovia-csmith** [comment]
No nothing comes back in regards to the File Structure Analysis. The whole page is disabled, although I edited the HTML to remove that element that was preventing me from interacting with the app and was not able to find anything that fit your description. Maybe a screenshot directing me to where you want me to check could be helpful?

**Comment by kiadso** [comment]
Hi, sure-

![Annotation 2022-12-21 152327](https://user-images.githubusercontent.com/7561522/208996404-6da42494-6592-4ba4-aff1-2cc24a91c086.png)

Where the gray drawn lines are ^

**Comment by eccovia-csmith** [comment]
Ah I see. I didn't notice it change from the default after uploading. 
![image](https://user-images.githubusercontent.com/98985084/208998827-b1d804fc-73b1-496a-b782-9174832d8f89.png)

**Comment by kiadso** [comment]
Ok, thank you for that screenshot, Eccovia- that really helped! There should be a table there, even if it's empty.

Can @eanders and @eccovia-csmith verify that your HMIS CSV Exports have the following files in it (with exactly these spellings)?

```"Assessment",
  "Client",
  "CurrentLivingSituation",
  "EmploymentEducation",
  "Enrollment",
  "EnrollmentCoC",
  "Event",
  "Exit",
  "Export",
  "Funder",
  "HealthAndDV",
  "IncomeBenefits",
  "Inventory",
  "Organization",
  "Project",
  "ProjectCoC",
  "Services",
  "User",
  "YouthEducationStatus"
```

For now, we are not pulling in or checking Disabilities, Affiliation, and the AssessmentQuestions, -Results ones but we will be eventually.

We're fixing it so that Eva will handle missing or misspelled csv files in a nicer way, but just thought I'd check to see if this may be the issue you two are experiencing!

Thanks for your patience!

**Comment by kiadso** [comment]
Hi you two,

A new version of Eva will be pushed today to address both of your issues. 

- Smith: if an export is uploaded that doesn't contain all the necessary files, the file will be rejected and list out what files are missing. 
- Elliot: if a column that is used in Eva contains nulls where there shouldn't be any, the file will be rejected and the File Structure Analysis will indicate which column(s) has/have those nulls. These are considered file structure issues because the CSV specs state that no nulls are allowed in these columns.

I'll close this issue once the new version is pushed to live. Feel free to reopen if there are further issues.

Thanks again for your help in tracking the issues down! :) @eanders @eccovia-csmith

**Comment by kiadso** [comment]
Closing this, since the fixes were pushed to Eva live
