### ISSUE TITLE
System level data quality report: possible overlaps issue

### ISSUE THREAD

**Issue by trevinflick** [abtassociates/eva#130]
**Describe the bug**
System level data quality report overlaps tab is showing enrollment overlaps that are according to the HUD data standards.

PreviousExitDate is showing NA when our Clarity HMIS shows an exit date that has not been edited.

**To Reproduce**
1. Upload hashed CSV
2. Run system data quality report
3. Download output file
4. Go to outputs tab
5. Some rows show PreviousExitDate as NA when they shouldn't

**Expected behavior**
Correct previous exit date shown.

**Screenshots**
![Screen Shot 2022-12-22 at 12 55 49 PM (2)](https://user-images.githubusercontent.com/6234452/209197080-948c72a2-0928-498d-9931-05de14b3f8a1.png)

**Desktop (please complete the following information):**
 - Operating System: MacOS
 - Browser: [What is my browser?] Chrome

**Comment by kiadso** [comment]
Thanks for reporting this- As we discussed, this appears to be an issue between the HMIS and the export, not the export and Eva. Reopen if anything changes!

**Comment by entomacy** [comment]
I think the issue that Trevin submitted is related to move-in dates after the HUD CSV report end date. Eva was showing us we had an overlap because a client in program A exited on 10/14/22, outside of our reporting period. (The exit did not appear in Exit.csv), but Eva included the 10/14/22 move-in date on the Program B enrollment that the client entered in 7/2022. Our reporting date ranges were 10/1/21 to 9/30/22.

**Comment by kiadso** [comment]
Ok, so assuming the enrollment into Project A had an Entry Date prior to the Report End, the issue is that that Enrollment's Exit record was not included in the export, correct? (It should have been, if it was entered when the export was run.)

**Comment by entomacy** [comment]
> the issue is that that Enrollment's Exit record was not included in the export, correct? (It should have been, if it was entered when the export was run.)

Is this real life? The exit was recorded on 10/18/22 and the exit date was 10/14/22. The report end date was 9/30/22 and I ran the report 12/15/2022. You're saying that Bitfocus should have included this exit in the Exit.csv despite that it's outside of the reporting end date?

**Comment by kiadso** [comment]
Hi, yes, please see the [HMIS CSV Format Specifications FY2022](https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.3.pdf), pages 5-6 under the section titled "Export Characteristics > Export Period Types > Reporting Period"

**Comment by entomacy** [comment]
> • Project Exit Date is null OR Project Exit Date is on or after the Export Start Date

is the only thing I saw in that page range that gets at this issue and it isn't 100% clear. I think that the vendor could argue that this could be exit date could be null because it is after the Export End Date. Am I missing something that more clearly outlines this expectation?

Is this a known issue with Clarity HUD CSV Exports? This seems like a pretty big deal that would impact a lot of work. I can't imagine that I'm the first person to notice this, assuing the Exit.csv is actually wrong.

**Comment by kiadso** [comment]
Exit dates after the Export Start Date would include Exit dates after the Export End Date, so yes, any Exit Dates after the Export End Date that exist in the system should be included in Exit.csv.

**Comment by entomacy** [comment]
OK, thank you! I will put in a ticket to Bitfocus now.
