### ISSUE TITLE
Records with missing Client Location

### ISSUE THREAD

**Issue by jonmagee** [abtassociates/eva#189]
Currently, Eva will not accept a CSV if the EnrollmentCoC.CoCCode is null.  In the CSV specs, it states _**"Fields that may be null are identified with a Y (for Yes). Any field not specifically permitted to be null should have an exported value of the appropriate data type; for non-nullable fields with response categories defined in the HMIS Data Dictionary, 99 (Data not collected) should be exported for blank fields / missing data.**_".  It's also true that for the particular field, in the CSV specs it does not have a "Y", meaning that it may not be left null.   However, the above sentence states _**"...with response categories defined in the HMIS Data Dictionary"**_.   This element does not have a response category defined in the HMIS Data Dictionary though. What should happen then, in this case?  Thanks for any clarification you can provide on this.

**Comment by vlopez0603** [comment]
Hello!

Per the HMIS CSV Specifications, the EnrollmentCoC.csv includes data from data element 3.16 Client Location. In keeping with relational database principles and the fact that no nulls are allowed for the CoCCode column, if there is no “ClientLocation” (aka CoCCode), there should not be a record in EnrollmentCoC since there is no observation to report.

We hope to clarify this in the upcoming version of the HMIS CSV Specifications.

**Comment by vlopez0603** [comment]
Closing this out. Please let us know if you have any further questions on this!
