### ISSUE TITLE
No data showing

### ISSUE THREAD

**Issue by soniawmeyer** [abtassociates/eva#265]
I can successfully upload an HMIS export, but nothing shows up in Eva.

**Comment by kiadso** [comment]
Hi @soniawmeyer ,
Can you send screenshots of what you are seeing once you upload your file?
Thank you!

**Comment by kiadso** [comment]
Hi @soniawmeyer, 

We are unable to recreate this issue in Eva. If you are still having this problem, please re-open this Issue so we can help you get the analyses you are looking for. We can set up a call or if you can post screenshots of what you are seeing, we can help you here. 

A previous similar issue was resolved by the user going to the Client Counts report and checking which projects were listed in the droplist there. He was only seeing a single (empty) project there because of the way he had run the export from his HMIS, so Eva wasn't finding any data to analyse. He resolved the issue by following instructions about how to run his hashed HMIS CSV export from his particular HMIS. If you are unsure about how to run your hashed HMIS CSV Export, please contact your HMIS vendor.

Thanks!
