### ISSUE TITLE
Eva error:  "Incomplete Living Situation Data"

### ISSUE THREAD

**Issue by MDHTRH** [abtassociates/eva#292]
Hi Github:

We are getting errors from Eva that clients are getting error msgs re:   "Incomplete Living Situation Data"  

It appears to be happening with clients where Previous Living Situation = "Staying with family or friends" before coming into either a SSVF Prevention/RRH pgm.  The GUIDANCE tab explanation says that the system needs to verify a client's chronicity or homelessness (?) or something similar to that. 
 
I asked Wellsky about this and they said to report it to you because they think this is an issue with Eva. 

Please advise.

Thx.

**Comment by kiadso** [comment]
Hi MD,

Can you please describe the contents of the Word documents you posted? We want to be sure there is no client-level data in them before we open them. 

Thank you-

Genelle

**Comment by MDHTRH** [comment]
Hi Genelle:
The screen print I have sent is a little snippet from the Eva "Error" tab that shows Organization, Project id, Project name, Issue, Personal id #, Entry date.   

Issue contains "Incomplete Living Situation Data" and Personal id contains the client number that Eva has identified as having this issue.  No identifying client level information is included or attached, ie, no client name, SSN or DOB information.

**Comment by kiadso** [comment]
Hi @MDHTRH,

So sorry for the delay in response and thank you for this question!

For "Incomplete Living Situation," the Guidance currently reads (minus the typo):

> When responding to the Prior Living Situation questions in your assessment at Project Start, users must answer questions about the clients' situation prior to the \"Type of Residence\" question that are important to help determine that client's Chronicity. Please answer these questions to the best of your knowledge.

A better description of why this is being flagged is that this HoH or adult entered a TH, PSH, SSO, HP, or RRH project and either

- the Living Situation was institutional and Length of Stay was 30 days or less and some required dependent data element is missing - OR -
- the Living Situation was permanent and Length of Stay was 7 days or less and some required dependent data element is missing.

Your original question says this is flagging whenever your client is coming into an RRH or HP from a permanent housing situation. For these clients, users should be answering: 

- Living Situation
- Length of Stay in prior living situation
- Did the client stay less than 7 nights?
- If yes to the previous question: On the night before, did the client stay on the streets, ES or SH?
- If yes to the previous question:
    - Date Homelessness Started
    - Number of times the client has been on the streets, in ES, or SH in the past three years
    - Number of months the client has been on the streets, in ES, or SH in the past three years

The guidance as it is currently written is directing users to be sure all of the necessary Living Situation questions are answered, depending on which ones would have been needed in a given scenario. The comment about Chronicity is meant to explain why these data elements are important to collect since they figure prominently in calculating Chronic status.

We'll revisit the wording of the guidance, but with the current information, we are thinking that Eva is flagging correctly. If you are seeing valid responses to each question listed above, please reply back here.

One thing to check is that your Length of Stay response is valid as of FY2022. In prior iterations of the Data Standards, they were a little different. The valid responses for Length of Stay are:

- One night or less
- Two to six nights
- One week or more, but less than one month
- One month of more, but less than 90 days
- 90 days or more, but less than one year
- One year or longer
- [client doesn't know/refused/data not collected]

Hope this helps, and thank you for your patience!

**Comment by RWHumboldt** [comment]
I am having a similar issue, but the prior living situation is "residential project or halfway house with no homeless criteria", length of stay in previous place is one month or more but less than 90 days. Did you stay less than 7 nights is "no." Halfway houses are categorized as "Temporary and Permanent Housing Situations" in the data standards. Could you provide guidance on why this is being flagged as an error?

**Comment by MDHTRH** [comment]
Hi:

The EVA report come up with the errors.  I have no idea why Eva flagged those items as errors.

All I know is....github said that some of these items were going to be obsoleted at the start of the new fiscal yr beginning on 10/1/23 and I was waiting for that magic date.

Can I help with anything else ?
________________________________

**Comment by RWHumboldt** [comment]
@MDHTRH my question was for the Abt team but thanks for the info

**Comment by MDHTRH** [comment]
Good morning Eva friends:

There were a number of items that I had inquired about in the github case that I submitted a couple months ago.

Just wanted to re-verify that this scenario was one of them as well:

So we have a family of 3 that entered a RRH pgm on 12/16/22.  On 12/27/22 the 2 that are not HoH exited back to the street, leaving the HoH who goes on to move into housing by himself on 1/01/23.

My user just ran an Eva rpt and the 2 clients that exited on 12/27/22 back to the street are getting "Invalid Move In Date" errors.

I don't think this is an error even though Eva is reporting it as an error.

Is this an issue that can be looked into ASAP ?

Thanks.



________________________________

**Comment by MDHTRH** [comment]
Hi:

I created a new case #356 for the HMID issue in case anyone wanted one.

Thx.
________________________________

**Comment by kiadso** [comment]
Something I would recommend to both @MDHTRH and @RWHumboldt:

One thing to check is that your Length of Stay response is valid as of FY2022. In prior iterations of the Data Standards, they were a little different. The valid responses for Length of Stay are:

- One night or less
- Two to six nights
- One week or more, but less than one month
- One month of more, but less than 90 days
- 90 days or more, but less than one year
- One year or longer
- [client doesn't know/refused/data not collected]

I know in my days as an admin, we had several values in our data that referred to the old "One week or less" response to Length of Stay, which is no longer a valid response, as of the FY2014 data standards. These responses should have been updated from "One week or less" to either "One night or less" or "Two to six nights". We had to fix them all in the data since the "one week or less" value couldn't be mapped to the new responses.

Hope this helps, and thank you for your patience!

**Comment by RWHumboldt** [comment]
@kiadso I am getting this error for a client where everything appears to be correct. The assessment file looks like this for the client enrollment that is causing the error:

LivingSituation 329
RentalSubsidyType null
LengthOfStay 3
LOSUnderThreshold 0
PreviousStreetESSH null
DateToStreetESSH null
TimesHomelessPastThreeYears null
MonthsHomelessPastThreeYears null

I'm not seeing anything wrong here- the client was not literally homeless or chronically homeless when they admitted the person to this PSH project. He'd been living in a residential project or halfway house for more than a month. What is the problem here?
