### ISSUE TITLE
Unsuccessful Upload: Your HMIS CSV Export is not structurally valid

### ISSUE THREAD

**Issue by jkivanc** [abtassociates/eva#312]
**Is your feature request related to a problem? Please describe.**
After downloading the appropriate CSV from HMIS, when we go to upload the file into EVA, we receive this message:  

_Unsuccessful Upload: Your HMIS CSV Export is not structurally valid
Your HMIS CSV Export has some High Priority issues that must be addressed by your HMIS Vendor. Please download the File Structure Analysis for details._

**Describe the solution you'd like**
Right now, because of the number of times this error is appearing, we are unable to functionally use EVA.  It seems strange that this tool, that we would like to use for DQ, requires DQ prior to use.  This is a huge barrier for us and renders this tool useless to us.

It would be amazing if we could upload the file into EVA and then interact with the errors and other DQ issues from with EVA.  

**Describe alternatives you've considered**
We have tried to trouble shoot the error and have "downloaded Structure Analysis Detail".  There were times when this was helpful and pointed us in the right direction to fix the CSV...but mainly the error left us confused.

**Comment by kiadso** [comment]
Hi @jkivanc,

Thank you for visiting Eva and uploading your file. What kinds of structure issues are you seeing in the File Structure Analysis?

When Eva rejects an upload, it means the structure of the HMIS CSV Export from your software is not in alignment with HUD specifications. This noncompliance with standards can cause unexpected errors in analyses that Eva is built to run, so instead of trying to account for any kind of variance in structure, Eva is requiring that all exports comply with the HUD specifications. As an example, Entry and Exit dates must be formatted like yyyy-mm-dd according to the HUD specifications. This is controlled by your vendor, and if they are formatted in a different way, Eva will not try to read the data because the code using those dates is written assuming they are in the right format. If they were in mm-dd-yyyy format, the code may error out and cause the app to crash. So to keep things stable, Eva requires those dates to be yyyy-mm-dd, in alignment with the HUD specs.

As such, these issues are best resolved by your HMIS vendor. Please share the list of High Priority issues with your vendor so they can correct the structure of their HMIS CSV Export and you can use Eva. 

All that said, there are some structural issues that you can account for manually while you wait on your vendor to make corrections, so if you wanted to share your list of issues, you can send them to genelle_denzin at abtassoc dot com and maybe I can help you work around those structural issues.
