### ISSUE TITLE
Structural Analysis Errors

### ISSUE THREAD

**Issue by jeript** [abtassociates/eva#333]
After uploading a hashed CSV to Eva, some admins in our implementation are receiving the following pop-up message: Your HMIS CSV Export has some High Priority issues that must be addressed by your HMIS Vendor.

The File Structure Analysis has errors that they can fix themselves. Most commonly, the errors are:
Null values in AssessmentType and AssessmentLevel in the Assessment file.
Clients with missing CoCCode in the Enrollment file.
Missing OperatingStartDate in Project file.
Missing Geocode in the ProjectCoC file.

The row numbers indicated on the File Structure Analysis Report are one less than the actual location in the csv file.

**Comment by jeript** [comment]
[File-Structure-Analysis-2023-08-17.xlsx](https://github.com/abtassociates/eva/files/12369700/File-Structure-Analysis-2023-08-17.xlsx)

**Comment by kiadso** [comment]
Hi @jeript, 

Thanks for the info. Your vendor's HMIS CSV Export should not contain any EnrollmentCoC records where CoC is null. (This is based on the [HMIS CSV Export Specifications](https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.3.pdf).) Since it does, you can either share this with your vendor and wait for them to correct their export or you can populate the CoC data element manually using the information in the EnrollmentCoC.csv file. (Or you can do both!)

The other issues in your file are classified as Errors, which means that if you don't fix them, Eva will still accept your export. You may still want to share this file with your vendor though, since the nulls flagged are technically not allowed in the export.

The row numbers listed refer to which row in the data, not including the header. You may be looking at the row numbers you see in Excel, which do include the header row.

Hope this helps!

**Comment by jeript** [comment]
Thank you. I'll let them know.

**Comment by jeript** [comment]
I knew it was the header, but it will confuse the Admins in our implementation. I'll add it to my instructions for them.

**Comment by jeript** [comment]
Are you saying I need to tell the vendor to generate an error when there are nulls?

**Comment by kiadso** [comment]
Hi, no, your vendor should be alerted to the fact that the export contains nulls in columns where they should not exist. If an Enrollment does not have an EnrollmentCoC (aka Client Location) saved, there should be no corresponding record in the EnrollmentCoC.csv file. The export specifications don't allow for nulls there so they should not exist in the export.

Your File Structure Analysis isn't meant to be sent to HMIS users/case managers, it's written for HMIS vendors since this is a structural issue. The Eva exports that go to your HMIS users/case managers are in the Data Quality section of Eva, which you will see once your export can pass the structural requirements.
