### ISSUE TITLE
Eva report results vary depending on user and the mode they are in when generating hashed CSV files

### ISSUE THREAD

**Issue by RWHumboldt** [abtassociates/eva#351]
I don't know that this is a bug, but we have discovered that the errors and warnings that appear in the Eva report depend on which user generated the report, whether they were "entering data as" a project or not, and the particular project they were "entering data as." We have WellSky software. When a system administrator runs hashed CSV export the results are accurate, but we wanted the agencies to be able to run the reports and get the same results that a system administrator would get, but apparently this is not possible. Depending on what mode the user is in when running the hashed csv export, they get errors showing up in the Eva report that do not appear in the system and also do not appear in the Eva report if they are entering data as the project they are creating a hashed csv file for. Unfortunately, this means it's only possible for the users to do Eva reports on one project at a time, and when they do, they don't get all the errors in the Eva report that a system admin sees when they run the report on the same project.

We had a closed HMIS that is now theoretically open, but we still have thousands of client records with closed visibility settings. If we updated the visibility settings for every client record in the system, I am thinking that would resolve the issue.

Given these conditions we were curious if the hashed CSV export is working the way it should on the vendor side?

**Comment by jessefjorstad** [comment]
Hi Robert,

I can verify that if the exports contain different data, Eva will produce different results. Can you confirm that is the case, so that we can rule this out as a bug? 

As to your question about the hashed CSV, I have reached out to a couple of colleagues and am awaiting a point of clarification. We'll be in touch soon.

**Comment by RWHumboldt** [comment]
Confirmed. I suppose my question is whether the hashed CSV export from WellSky is working as intended.

**Comment by jessefjorstad** [comment]
Hi Robert,

This question falls outside of Eva's intended use (designed for HMIS administrators) and of HUD's requirements for vendors. We don't know why the .csv files are different and can't say whether those .csv files are working as intended because this is not specified by HUD. You might want to follow-up on this with WellSky to understand how their privacy and security model could be best leveraged to ensure that users have access to the records they are expecting to see when exporting data.

**Comment by RWHumboldt** [comment]
We're looking at doing an HMIS RFP and I'm curious if you know whether people with other HMIS vendors are having similar issues?
