### ISSUE TITLE
What does EVA error stating “Long Stayers (Outliers) mean and how do I fix it?

### ISSUE THREAD

**Issue by crtfly** [abtassociates/eva#362]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: [What is my OS?](https://whatsmyos.com/)
 - Browser: [What is my browser?](https://www.whatismybrowser.com/)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alex-silverman** [comment]
Hello - As per the guidance provided by Eva, this is a warning that is flagged when:

  "This household has been housed in your project for a relatively long time compared to enrollments into the same project type in the rest of your system."

It is not an error, and thus does not need to be fixed. However, as per the guidance:

  "If they have exited, please enter an Exit Date, otherwise consider using Move On Assistance funds. If they need to remain in the project, leave everything as is."

Does that answer your question? Happy to provide more clarification if needed!
