### ISSUE TITLE
Destination question

### ISSUE THREAD

**Issue by crtfly** [abtassociates/eva#363]
If project lost contact with a client and did not do an exit interview, which response do you want us to use?

**Comment by alex-silverman** [comment]
Hello - please see page 152 of the [HMIS manual](https://files.hudexchange.info/resources/documents/HMIS-Data-Standards-Manual-2024.pdf). That may have the information needed to answer your question. If not, please [submit an AAQ](https://www.hudexchange.info/program-support/). 

BTW, as you may know, Eva is really meant for HMIS admins. If you are not an HMIS admin, you should contact your HMIS admin about this issue.

**Comment by crtfly** [comment]
I am an HMIS SysAdmin, if perhaps a stupid one. Anyway, I know what the HUD responses are. What I want to know is what does EVA want for a response when no exit interview was conducted?

**Comment by alex-silverman** [comment]
I think this one may be on me for not understanding your question. I assume Eva's DQ checks are flagging a warning like "Don't Know/Refused Destination", or "Missing Destination", or "Long Stayers", and you're wondering what value to put in the "Destination" field when no exit interview was conducted. Is that right? If so, I think you can leave the data as-is. These are just warnings in case the data are actually incomplete or otherwise incorrect. But if they're correct, you need not change anything.

**Comment by kiadso** [comment]
@crtfly Alex is correct- please see the definitions of the different issue types that Eva has:

High Priority Errors

- Always indicates a data quality issue that can and should be fixed in HMIS.
- Aim for 0 High Priority errors.
- These errors affect multiple federal reports in a fundamental way and thus should be prioritized.

General Errors

- Always indicates a data quality issue that can and should be fixed in HMIS.
- Aim for 0 General Errors.

Warnings

- May be a data quality issue, but may also be an unexpected situation that reflects reality.
- Do not aim for 0 Warnings. It is ok and expected to have some warnings.
- End users should check that any data being flagged as a Warning is accurate in their HMIS. If it is not accurate, then it should be corrected. If it is accurate, it should be left as is.
