### ISSUE TITLE
Destination Error 

### ISSUE THREAD

**Issue by Nancye28** [abtassociates/eva#409]
It appears EVA is indicating that the destination is "Missing" when the Destination = "Exit Interview Not Completed." under the "Warnings" tab.

Is this expected behavior?

**Comment by kiadso** [comment]
Hi Nancy,

Yes, since the Destination wasn't collected (because there was no exit interview), that data is considered missing. It isn't "missing" in the sense that there's a value saved to the data element, but the information about what the destination of the household was is missing. It's classified as a Warning since it's likely an accurate answer and thus can't be corrected. 

Remember how Eva classifies the issues it finds: This app categorizes every issue it finds in your data set in terms of its severity.

**High Priority Errors**

- Always indicates a data quality issue that can and should be fixed in HMIS.
- Aim for 0 High Priority errors.
- These errors affect multiple federal reports in a fundamental way and thus should be prioritized.

**General Errors**

- Always indicates a data quality issue that can and should be fixed in HMIS.
- Aim for 0 General Errors.

**Warnings**

- May be a data quality issue, but may also be an unexpected situation that reflects reality.
- Do not aim for 0 Warnings. It is ok and expected to have some warnings.
- End users should check that any data being flagged as a Warning is accurate in their HMIS. If it is not accurate, then it should be corrected. If it is accurate, it should be left as is.
