### ISSUE TITLE
Invalid Move-In date error for projects without operating end dates.

### ISSUE THREAD

**Issue by LynnSharpe** [abtassociates/eva#422]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
I ran an EVA upload for FFY23 and received many errors for 'Invalid Move-In date,' while digging into it, most of them don't seem to be errors, and they are all associated with projects without an operating end date. 

In that same export, I found a lot of other errors surrounding exit dates and projects without operating end dates. Specifically, 'Enrollment Crosses Operating End, Enrollment Crosses Participating End, and Project Exit Before Start' came up.

Is the move-in date something that could be impacted by the project operating end date?

**To Reproduce**
Generate a CSV export from HMIS for FFY23, upload to Eva, and export the Data Quality Report. Review Error's tab.
Use the Programs CSV file to verify if the program as an operating end date, and compare it to the errors 
Enrollment Crosses Operating End
Enrollment Crosses Participating End
Project Exit Before Start
and (maybe) Invalid Move-In Date

**Expected behavior**
Errors in exit dates/move-in dates shouldn't appear for projects that don't have operating end dates, when otherwise valid.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating System: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kiadso** [comment]
Hi Lynn,

Thank you for reporting these issues. So we can better understand what you're seeing, can you (without sending any PII) send some examples as described below that we can work with? I'm not understanding the relationship you're describing between whether a project has an Operating End Date and some of these issues that flagged. 

1. For the issue called, "Enrollment Crosses Operating End":

- ProjectID of an Enrollment being flagged
- ProjectID's Operating Start Date
- ProjectID's Operating End Date (if any)
- Enrollment's Project Start Date (aka Entry Date) and Project Exit Date (if any)

The "guidance" for this issue is: **This enrollment ends after the project stopped operating. For reporting to work correctly, be sure your enrollment dates are within your HMIS participation dates.**

2. For the issue called, "Enrollment Crosses Participating End":

- ProjectID of an Enrollment being flagged
- ProjectID's HMIS Participating Start Date and End Date (if there are more than HMISParticipation records, please share each one)
- Enrollment's Project Start Date (aka Entry Date) and Project Exit Date

The "guidance" for this issue is: **This enrollment ends after the project stopped participating in HMIS. For reporting to work correctly, be sure your enrollment dates are within your HMIS participation dates.**

3. For the issue called, "Project Exit Before Start":

- A flagged Enrollment's Project Start Date (aka Entry Date)
- Enrollment's Project Exit Date (if any)

The "guidance" for this issue is: **This enrollment ends after the project stopped participating in HMIS. For reporting to work correctly, be sure your enrollment dates are within your HMIS participation dates.**

4. For the issue called, "Invalid Move-In Date":

- A flagged Enrollment's Project Start Date (aka Entry Date)
- Enrollment's Housing Move-In Date
- Enrollment's Project Exit Date (if any)


Thank you for the detail, this will help us determine where the issues are.

-Genelle

**Comment by kiadso** [comment]
Hi Lynn, [updated comment, please disregard the previous one]

Thank you for reporting these issues. So we can better understand what you're seeing, can you (without sending any PII) send some examples as described below that we can work with? I'm not understanding the relationship you're describing between whether a project has an Operating End Date and some of these issues that flagged. 

1. For the issue called, "Enrollment Crosses Operating End":

- ProjectID of an Enrollment being flagged
- ProjectID's Operating Start Date
- ProjectID's Operating End Date (if any)
- Enrollment's Project Start Date (aka Entry Date) and Project Exit Date (if any)

The "guidance" for this issue is: **This enrollment ends after the project stopped operating. For reporting to work correctly, be sure your enrollment dates are within your HMIS participation dates.**

2. For the issue called, "Enrollment Crosses Participating End":

- ProjectID of an Enrollment being flagged
- ProjectID's HMIS Participating Start Date and End Date (if there are more than HMISParticipation records, please share each one)
- Enrollment's Project Start Date (aka Entry Date) and Project Exit Date

The "guidance" for this issue is: **This enrollment ends after the project stopped participating in HMIS. For reporting to work correctly, be sure your enrollment dates are within your HMIS participation dates.**

3. For the issue called, "Project Exit Before Start":

- A flagged Enrollment's Project Start Date (aka Entry Date)
- Enrollment's Project Exit Date (if any)

The "guidance" for this issue is: **This enrollment's exit date is before the enrollment's project start date. The exit date must be after or equal to the project start date. Please go to this enrollment and ensure that the correct project start date and exit date are entered.**

4. For the issue called, "Invalid Move-In Date":

- A flagged Enrollment's Project Start Date (aka Entry Date)
- Enrollment's Housing Move-In Date
- Enrollment's Project Exit Date (if any)

The "guidance" for this issue is: **This move-in date does not fall between the Entry Date and the Exit Date or this move-in date is after the Export End Date. Please review and correct.**

Thank you for the detail, this will help us determine where the issues are.

-Genelle

**Comment by LynnSharpe** [comment]
Hi Genelle,
Thank you for looking into this! I've attached a spreadsheet with the data
you've requested (nothing identifying, of course).

For the issue called "Enrollment Crosses Operating End": See tab A
For the issue called, "Enrollment Crosses Participating End": See tab B
For the issue called, "Project Exit Before Start": See tab C
For the issue called, "Invalid Move-In Date": See tab D


I generated my CSV file on 11/6/23, for FFY23, for all projects in our
multi-CoC implementation.

Please let me know if there is anything else I can do to help.

Thank you,
*Lynn Sharpe, MBA *| She/Her/Hers | UHMIS System Administrator
Phone: 385.258.4196
 | Email:
 ***@***.***
Website: jobs.utah.gov/housing and UtahHMIS.org

**Comment by kiadso** [comment]
Hi Lynn,

Can you post the workbook here on GitHub? Whenever you attach a file to an email, we don't get it.

ALSO, could you try Eva again and let us know if you're still getting the same issues? We just applied a number of hotfixes to Eva and maybe they affected what you're seeing.

Thanks-
Genelle

**Comment by LynnSharpe** [comment]
Here is the file that I sent via email:
[Abt Associates Issue (Issue #422).xlsx](https://github.com/abtassociates/eva/files/13311220/Abt.Associates.Issue.Issue.422.xlsx)

When I re-uploaded the same CSV, I got this high-priority error, so I could not identify if the other errors appeared.
[File-Structure-Analysis-2023-11-09.xlsx](https://github.com/abtassociates/eva/files/13311265/File-Structure-Analysis-2023-11-09.xlsx)

**Comment by kiadso** [comment]
Hi @LynnSharpe,
Thank you so much for the workbook with all the examples. The short answer is that if you run your file through today (instead of 9/30/2023, say) a lot of these should go away. That is not to say you shouldn't run your file with an Export End Date that's in the past, but Eva is going through a thorough review of how dates are being handled right now and we're aware that this is something that needs to be accounted for. But until we get that sorted, you can run your file through today and be fine.
Also we did an update yesterday that should fix the 'Invalid Move-In Date' and 'Project Exit Before Start' ones I think, but if you could verify that those are fixed, that would be great.
Thanks for your patience, and I'll update back here once we update again next week (Thursday) with the broader date changes so you can run your file with a different Export End Date than "today."
Cheers,
Genelle

**Comment by LynnSharpe** [comment]
Hi Genelle,
Both the 'Invalid Move-in Date' and 'Project Exit Before Start' errors seem to work correctly; while we still have a handful of each, they are valid errors that we can adjust.

I'll close this ticket and watch the update notes for the change to allow us to run it for an end date that isn't the day it is uploaded to Eva.

Thank you!

**Comment by kiadso** [comment]
Great- thank you!
