### ISSUE TITLE
Failure to upload

### ISSUE THREAD

**Issue by ksexton11** [abtassociates/eva#475]
A File Structure Analysis issue, where the HouseholdID not incrementing correctly. The Household ID h_1956360, which are with clients 382226, 382227, and 206094. Our vendor has said the following. 

The household ID is erroneously referenced across multiple project enrollments. It's almost like the results of the analysis from the Live export have been "cached" and are just continuing to appear, despite the fact that the newer zip file has corrected the issue.

Therefore Eva fails to accept the upload.

**Expected behavior**
Eva fails to accept the upload

**Desktop (please complete the following information):**
 - Operating System: Dell
 - Browser: [What is my browser?] Google Chrome

**Additional context**

**Comment by kiadso** [comment]
Hi @ksexton11 ,
Thanks for your patience! From my reading of your vendor's response, this is either a vendor issue or it has to do with the way you're running the export, but I am looking further into it. 
I will respond back here once I know more.

**Comment by kiadso** [comment]
Hi @ksexton11, please let us know if you hear anything further from your vendor that this is an Eva issue. Since your vendor stated, "The household ID is erroneously referenced across multiple project enrollments," we think this means it is a problem in your export and not on the Eva side, but if you hear otherwise, please re-open this issue.

Thank you!
