### ISSUE TITLE
Incomplete Living Situation Error

### ISSUE THREAD

**Issue by LynnSharpe** [abtassociates/eva#490]
**DO NOT UPLOAD YOUR EXPORT TO GITHUB**

**Describe the bug**
For clients whose prior living situation location is a 'Residential project or halfway house with no homeless criteria,' and the question did you stay less than seven nights is answered 'No.' 

We get the 'Incomplete Living Situation,' even though the length of stay in the prior living situation is longer than seven days. 

**To Reproduce**
1. Generate a CSV export with at least one client whose prior living situation is a 'Residential project or halfway house with no homeless criteria,' the question did you stay less than seven nights is answered 'No,' and select a length of time greater than one week. 
2. Upload the CSV into Eva and export the full data quality report.
3. Look for the error 'incomplete living situation' for the enrollment.

**Expected behavior**
Eva should not identify this particular response sequence as an error, as it is not missing any information.

**Screenshots**
I have not taken any screenshots, but I can provide de-identified ones if needed.

**Desktop (please complete the following information):**
 - Operating System: Windows 11
 - Browser: Google Chrome
 -
**Smartphone (please complete the following information):**
N/A

**Additional context**
Nope, but I appreciate this tool, it is very helpful!

**Comment by RWHumboldt** [comment]
I am having the same issue. A was in a "residential project or halfway house" for more than one month but less than 90 days immediately prior to entry into a PSH project. The enrollment file for this client has the following values:

LivingSituation: 329
Length of Stay: 3
LOSUnderThreshold: 0
PreviousStreetESSH: Null
DateToStreetESSH: Null
TimesHomelessPastThreeYears: Null
MonthsHomelessPastThreeYears: Null

We have another client in the same project who had the same prior living situation, but they were there for more than 90 days- that client's enrollment is not generating an incomplete prior living situation error in Eva. I am wondering if Eva is improperly treating living situation 329 Residential Project or Halfway House as an institutional setting, in which case the threshold for needing answers to the additional questions would be 90 days instead of 7 days, whereas the data dictionary Appendix A provides that this is a "temporary housing situation" so the threshold should be 7 days.

**Comment by kiadso** [comment]
Hi, you two are correct, we have living situation 329 as institutional. We are working on getting this corrected. Thank you both for documenting this for us and for your patience. @LynnSharpe @RWHumboldt

**Comment by alyssandrichik** [comment]
Hi @LynnSharpe and @RWHumboldt, we have resolved this living situation error in Eva! Thank you again for sharing this issue with us.
