### ISSUE TITLE
"Invalid Move In Date" error

### ISSUE THREAD

**Issue by MDHTRH** [abtassociates/eva#558]
GITHUB:
I can't remember if this has previously been reported or not but I'm going to describe a HMID situation again.

So I have a family that moves into a RRH pgm on 5/7/24 and everyone has a HMID of 5/7/24.   On 7/15/24 a new baby comes into the program Entry with entry start date of 7/15. 

Below are 3 test scenarios that I have tried with the baby and her Entry.  All 3 scenarios are giving the same ERROR when the Eva reports are run !  Note that baby's HMID 7/17 is after the Entry date of 7/15 but Eva doesn't seem to care and is still generating errors.  

**TEST SCENARIOS**
(1)  baby's HMID of 7/17 is filled in directly on the baby's Entry of 7/15
(2)  Interim date of 7/17 is created with a HMID of 7/17 
(3)  baby has no HMID on the Entry of 7/15 and has no Interim 

Here is the error report I keep getting back from Eva:
**Error:  Invalid Move-In Date  - This move-in date does not fall between the Entry Date and the Exit Date or this move-in date is after the  Export End Date.  Please review and correct**

Is this an issue GITHUB can address or provide any recommendations ?

Thx.

**Comment by kiadso** [comment]
Hi @MDHTRH, thanks for this question!

Just for clarity, here is the logic of the check:

ProjectType in RRH, PSH or OPH AND
    The MoveInDate is Less than the EntryDate OR
    The MoveInDate is Greater than the ExitDate

The baby does not need a HMID for HUD purposes; only heads of households need a HMID. That also means the other family members who are not the HoH would not need an HMID. See the FY2024 HUD HMIS Data Standards section about it: 
![image](https://github.com/user-attachments/assets/4b5908da-7e52-4b66-be5f-e407e405c27c)

So once you remove those Move-In Dates, that should resolve the errors for scenarios 1 and 2, unless something else is going on.

Regarding scenario 3: Since "Interim" is not a HUD data element or mechanism, this likely has something to do with your particular software. Eva only looks at what comes into the HMIS CSV Export. It may be true that your software's "Interims" affect how data comes into your CSV Export. 

Also, you should be able to add the baby to the household's current enrollment with a project start date = the child's DOB. The HUD HMIS Data Standards says: "If this client is a newborn baby, the ‘Project Start Date’ [aka the Entry Date] would reflect the date the project started providing housing or services to the newborn ... which may be any date on or after the baby's date of birth." 

Assuming you have your EntryDate correct and your HMID is null in your HMIS, can you open your CSV Export, open the Enrollment.csv in a text editor, locate an enrollment with the problem you describe in scenario 3, and check to see if the Move-In Date is null there as well? This will tell you if there's a misalignment between what is in your HMIS and what is being exported in the CSV Export. If there is a misalignment, please let us know and also contact your vendor.
 
Thanks!

**Comment by kiadso** [comment]
Hi @MDHTRH,
I'm going to go ahead and close this issue, but if you rerun your export, reupload to Eva, and are still seeing this issue, please let us know!
Thank you,
Eva dev team

**Comment by MDHTRH** [comment]
thank you.

Wellsky said they came out with some now HMID changes in a new release today.  We'll find out how this turns out.
________________________________
