### ISSUE TITLE
Missing Fields Not Accurate

### ISSUE THREAD

**Issue by fbradford7** [abtassociates/eva#564]
**Is your feature request related to a problem? Please describe.**
Eva flags fields answered as "client doesn't know" and "client prefers not to answer" as missing but these are valid answers per the data standards.

**Describe the solution you'd like**
I would like Eva to be able to decipher if a field has been answered "doesn't know" or "prefers not to answer" rather than information actually missing or "data not collected"

**Describe alternatives you've considered**
I manually check each answer for these missing fields

**Additional context**

**Comment by zabalad** [comment]
Hi @fbradford7,

Thank you for reaching out. We want to ensure we're on the same page in terms of how we define "missingness" in the context of Eva.
 
Currently, there are four possibilities for missingness in Eva: (1) Blank, (2) doesn't know, or 8 (3) prefers not to answer, or 9 (4) Data not collected, or 99.
 
Currently, blank values and "data not collected" are flagged as errors by Eva. "Doesn't know" and "prefers not to answer" are flagged as warnings by Eva, meaning that the system makes a note of it but does not treat the values as needing to be corrected.
 
It's worth noting that we are currently in the process of recategorizing "data not collected" as a warning rather than an error. Once we make this change, the only type of missingness that will be treated as an error moving forward will be blank entries. However, this change has not been made yet - we are still working on this.
 
But to address your request, which was to differentiate between doesn't know/prefer not to answer and true missing/data not collected - Eva currently does this already by differentiating between warnings and errors in the data quality checks. Below is a screenshot with the definitions of High Priority/Error/Warning (found in the Instructions on Eva):
![image](https://github.com/user-attachments/assets/ce149fdd-ea32-4e42-b414-cc782356ab2f)

Please let us know if this clarification helps to resolve your issue. If not, please follow up with additional details and/or a screenshot of your Eva validation output (please DO NOT include screenshots of your input data).

**Comment by zabalad** [comment]
Hi @shsdrc,

Thank you for bringing this to our attention. We looked into it, and our programs appear to be coded correctly. dkr_race only includes instances of RaceNone= 8 or 9 and correctly maps to checkIDs=63 in EvaChecks.csv, which has the Warning message "Doesn't Know/Prefers Not to Answer Race/Ethnicity", not the Error message "Missing Race/Ethnicity."
![image](https://github.com/user-attachments/assets/b0274a98-cac0-4086-ad37-fff45e2335f7)
![image](https://github.com/user-attachments/assets/f3b14867-2507-4f60-b63b-ad6b137f1fed)

Could you please send us a screenshot directly from the Eva output you receive after uploading your hashed file, censoring any sensitive/extraneous information?

**Comment by shsdrc** [comment]
Hi @zabalad, 

Please see the screenshot below of the export from Eva!
![image](https://github.com/user-attachments/assets/8428fdde-ce2f-4fa2-a2f2-01f15dfae317)
I've filtered it down to just the Missing Race/Ethnicity error that totaled 107 in this export. 

Looking at this export, we do have 75 warnings listed as Doesn't Know/Prefers Not to Answer Race/Ethnicity. However, 75 of the 8 and 9 responses are still getting listed under the error Missing Race/Ethnicity.
![image](https://github.com/user-attachments/assets/78cb9ac9-cf5b-45a6-ad99-574ab3bd42b0)

**Comment by shsdrc** [comment]
Update! I got curious that the count of errors and warning was the same for 8 and 9 response. I then found clients are receiving both a warning and an error. 
Shown in tableau:
![image](https://github.com/user-attachments/assets/3bf205a1-f53c-4288-aa71-fa188e24276a)
Filtered to a specific clientID starting with 20 in the EVA file
![image](https://github.com/user-attachments/assets/c8416f93-62b0-4f49-b32d-7f3c5731a008)
![image](https://github.com/user-attachments/assets/11de5060-478f-49e4-8f78-b259bab69872)

**Comment by zabalad** [comment]
Hi @shsdrc,

Thank you for investigating that, this is very helpful! We will be addressing this issue in a coming update and will let you know once we push the update.

**Comment by shsdrc** [comment]
Of course! This is duplication is also occurring for the missing gender error/prefers not to answer gender warning. Let me know if you'd like screenshots of that one as well.

**Comment by kiadso** [comment]
Hi @shsdrc and @fbradford7,

Eva has been updated with fixes for both of these issues. See the changelog for the way Eva now addresses nulls vs Data Not Collected, and we also removed the duplication that @shsdrc was noticing as part of this. Here's from the changelog:

> - Updated how 'Data not collected' is handled when Eva assesses data quality. Eva now classifies data elements marked in the export as 'Data not collected' as a Warning instead of as an Error, to align with Eva's Error and Warning definitions. This approach is aimed at helping HMIS end users focus on correcting fixable issues without changing accurate information. The Warning is meant to remind users to verify if the data might still be collected or if the data exists elsewhere, such as in the client's file. If 'Data not collected' is the correct value, users should leave the value as-is in HMIS. Issues that should be fixed in HMIS are categorized as Errors.
> - Removed logic that looks for nulls in specific data elements when Eva assesses data quality. For the Race/Ethnicity, Gender, Veteran Status, Disabling Condition, Name Data Quality, DOB Data Quality, SSN Data Quality, and Destination data elements, the HMIS CSV export does not distinguish between nulls and the value 'Data not collected' The issues removed are: Missing Name Data Quality, Missing DOB Data Quality, Missing SSN Data Quality, Missing Gender, Missing Veteran Status, Missing Disabling Condition, and Missing Destination. These are now flagged as Warnings and described as 'Unknown Gender,' 'Unknown Veteran Status,' etc.

Thanks for your patience, and please let us know if something is still unexpected
Eva dev team
