### ISSUE TITLE
Generate Error for Invalid Social Security Numbers

### ISSUE THREAD

**Issue by JLegg77** [abtassociates/eva#635]
Would it be possible to generate an error for Social Security Numbers when the social security number does not comply with the SSA rules.

From the HMIS Standard Reporting Terminology Glossary:

For all SSNs
▪ Cannot contain a non-numeric character (excludes any vendor-designated placeholder characters).
▪ The third group / last four digits must be present and cannot be “0000”.
– When the first three digits are present
▪ First three digits cannot be “000,” “666,” or in the 900 series

**Comment by kiadso** [comment]
Hi @JLegg77 

Eva does flag SSN Data Quality data that indicates a SSN that is not complete as Warnings, but Eva cannot do the kind of check you're looking for since the HMIS CSV Export you're uploading has to be hashed. The SSNs and names of all clients are obscured for security reasons, so this kind of analysis would need to happen either within your HMIS software or in a custom report generated by you or your HMIS vendor. Your software may already have something like this; you could check with your vendor about it. 

Thanks for asking! 
Eva dev team
