### ISSUE TITLE
EVA "Invalid Move-In Date"

### ISSUE THREAD

**Issue by susannarodriguez** [abtassociates/eva#648]
Getting the above issue on several PSH clients.  

The guidance says "This move-in date does not fall between the Entry Date and the Exit Date or this move-in date is after the Export End Date. Please review and correct."

It seems that the data does apply to the above.

For example:
Entry Date: 11/01/21
Move-In Date: 11/01/21 (transferred in place)
Exit Date: 07/31/24
Report Export Date: 11/06/24

If the EVA data is correct, what am I missing?

Thank you,
Susanna

**Comment by susannarodriguez** [comment]
Per Eva dev team
"If it does, please let us know. The code should not be flagging the example you listed above, as the Move-In Date is not less than the Entry Date, and I have verified that this is how the code is currently written"

The EVA report is not showing the correct move in date in the Enrollment.csv but it is correct in HMIS.

**Comment by kiadso** [comment]
Hi @susannarodriguez  ,

In order to figure out if Eva is doing something unexpected, can you tell us what your export says the Move-In Date is for the EnrollmentID in question?

If you download your Data Quality export for the organization in question, you can find the EnrollmentID that is getting flagged. Write that down, then open your export by unzipping it to a directory on your computer, then navigate to the Enrollment.csv and open that file in Excel or a text editor of your choice. Search up the EnrollmentID you wrote down and check that the Move-In Date there matches what you're seeing in your HMIS. If it does not, please contact your vendor. If it does, please let us know. The code should not be flagging the example you listed above, as the Move-In Date is not less than the Entry Date, and I have verified that this is how the code is currently written.

Good luck, and let us know how it goes!

Eva dev team

**Comment by kiadso** [comment]
Hi @susannarodriguez,
This means you need to contact your vendor and be sure that the Move-In Date in your Enrollment.csv matches the one in your HMIS. Please contact your vendor and once they have fixed it on their end, Eva will stop flagging these enrollments.
Eva dev team
